/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package cn.jm.happy.helloPlugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class StaticsPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.forEach {
            println "jiang ls: $it"
        }
        project.tasks.register("greeting") {
            doLast {
                println("rrr from plugin 'cn.jm.happy.helloPlugin.greeting'")
            }
        }
//        def isApp = project.plugins.hasPlugin(AppPlugin)
//        project "jiang is app: $isApp"
        //only application module needs this plugin to generate register code
//        def android = project.extensions.getByType(AppExtension)
//        def transformImpl = new StaticsTransform(project)

        //register this plugin
//        android.registerTransform(transformImpl)
    }
}
